[package]

name = "uuid"
version = "0.5.0"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/uuid"
homepage = "https://github.com/rust-lang/uuid"
documentation = "https://doc.rust-lang.org/uuid"
description = """
A library to generate and parse UUIDs.
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
rustc-serialize = { version = "0.3", optional = true }
serde = { version = "1.0", optional = true }
rand = { version = "0.3", optional = true }
sha-1 = { version = "^0.4.1", optional = true, default-features = false }
md-5 = { version = "^0.5.2", optional = true, default-features = false }

[features]
use_std = []
v3 = ["md-5"]
v4 = ["rand"]
v5 = ["sha-1"]
