[package]

name = "uuid"
version = "0.5.1"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/uuid"
homepage = "https://github.com/rust-lang/uuid"
documentation = "https://doc.rust-lang.org/uuid"
description = """
A library to generate and parse UUIDs.
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
serde = { version = "1.0.16", optional = true }
rand = { version = "0.4", optional = true }
sha1 = { version = "0.4", optional = true }
md5 = { version = "0.3", optional = true }

[dev-dependencies]
serde_test = "1.0.19"

[features]
std = []
v1 = []
v3 = ["md5"]
v4 = ["rand"]
v5 = ["sha1"]

[[bin]]
name = "uuid"
doc = false
