[package]

name = "uuid"
version = "0.6.3"
authors = [
        "Ashley Mannix<ashleymannix@live.com.au>",
        "Christopher Armstrong",
        "Dylan DPC<dylan.dpc@gmail.com>",
        "Hunar Roop Kahlon<hunar.roop@gmail.com>"
        ]
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/uuid-rs/uuid"
homepage = "https://github.com/uuid-rs/uuid"
documentation = "https://docs.rs/uuid"
description = """
A library to generate and parse UUIDs.
"""

[package.metadata.docs.rs]
all-features = true

[build-dependencies.rustc_version]
version = "0.2"

[dependencies]
serde = { version = "1.0.16", optional = true, default-features = false }
rand = { version = "0.4", optional = true }
sha1 = { version = "0.6", optional = true }
md5 = { version = "0.3", optional = true }
slog = { version = "2", optional = true }
cfg-if = "0.1.2"

[dev-dependencies]
serde_test = "1.0.19"

[features]
default = ["std"]
std = []
use_std = ["std"] # Compatibility shim for 0.5 and earlier
v1 = []
v3 = ["md5", "rand"]
v4 = ["rand"]
v5 = ["sha1", "rand"]

# Get features picked up by the Integer 32 playground. Not public API.
#
#    https://play.rust-lang.org
playground = ["serde", "v1", "v3", "v4", "v5"]

nightly = []
