[package]

name = "uuid"
version = "0.6.0"
authors = [
        "Ashley Mannix<ashleymannix@live.com.au>",
        "Christopher Armstrong",
        "Dylan DPC<dylan.dpc@gmail.com>",
        "Hunar Roop Kahlon<hunar.roop@gmail.com>"
        ]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/uuid-rs/uuid"
homepage = "https://github.com/uuid-rs/uuid"
documentation = "https://docs.rs/uuid"
description = """
A library to generate and parse UUIDs.
"""

[package.metadata.docs.rs]
all-features = true

[dependencies.md5]
optional = true
version = "0.3"

[dependencies.rand]
optional = true
version = "0.4"

[dependencies.serde]
default-features = false
optional = true
version = "1.0.16"

[dependencies.sha1]
optional = true
version = "0.5"

[dev-dependencies]
serde_test = "1.0.19"

[features]
default = ["std"]
std = []
use_std = ["std"] # Compatibility shim for 0.5 and earlier
v1 = []
v3 = ["md5"]
v4 = ["rand"]
v5 = ["sha1"]

[target."cfg(all(feature = \"rand\", feature = \"std\"))".features]
std = ["rand/std"]

[target."cfg(all(feature = \"serde\", feature = \"std\"))".features]
std = ["serde/std"]

[target."cfg(all(feature = \"sha1\", feature = \"std\"))".features]
std = ["sha1/std"]
