[package]
authors = [
    "Ashley Mannix<ashleymannix@live.com.au>",
    "Christopher Armstrong",
    "Dylan DPC<dylan.dpc@gmail.com>",
    "Hunar Roop Kahlon<hunar.roop@gmail.com>"
]
description = "A library to generate and parse UUIDs."
documentation = "https://docs.rs/uuid"
exclude = [
    ".github/**",
    ".travis.yml",
    "appveyor.yml",
    "bors.toml"
]
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/uuid-rs/uuid"
name = "uuid"
readme = "README.md"
repository = "https://github.com/uuid-rs/uuid"
version = "0.6.5"

[package.metadata.docs.rs]
all-features = true

[package.metadata.playground]
features = ["serde", "u128", "v1", "v3", "v4", "v5"]

[dependencies.byteorder]
default-features = false
features = ["i128"]
optional = true
version = "1"

[dependencies.md5]
optional = true
version = "0.3"

[dependencies.rand]
optional = true
version = "0.4"

[dependencies.serde]
default-features = false
optional = true
version = "1.0.46"

[dependencies.sha1]
optional = true
version = "0.6"

[dependencies.slog]
optional = true
version = "2"

[dev-dependencies.serde_test]
version = "1.0.46"

[features]
default = ["std"]
std = []
v1 = []
v3 = ["md5", "rand"]
v4 = ["rand"]
v5 = ["sha1", "rand"]

# deprecated
#------------------------
# Use `"std"` instead
use_std = ["std"]

# since rust 1.26.0
u128 = ["byteorder"]

# nightly rust
#------------------------
# Allow using `const fn`s
const_fn = ["nightly"]
# Nightly marker feature gate
nightly = []
