[package]

name = "uuid"
version = "0.1.17"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/uuid"
homepage = "https://github.com/rust-lang/uuid"
documentation = "http://doc.rust-lang.org/uuid"
description = """
A library to generate and parse UUIDs.
"""

[features]
v5 = ["sha1"]

[dependencies]
rustc-serialize = "0.3"
rand = "0.3"
sha1 = { version = "0.1.0", optional = true }
