[package]

name = "uuid"
version = "0.6.0-beta"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/uuid"
homepage = "https://github.com/rust-lang/uuid"
documentation = "https://docs.rs/uuid"
description = """
A library to generate and parse UUIDs.
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
serde = { version = "1.0.16", optional = true, default-features = false }
rand = { version = "0.4", optional = true }
sha1 = { version = "0.4", optional = true }
md5 = { version = "0.3", optional = true }

[dev-dependencies]
serde_test = "1.0.19"
criterion = "0.1.0"

[features]
default = ["std"]
std = []
v1 = []
v3 = ["md5"]
v4 = ["rand"]
v5 = ["sha1"]

[[bench]]
name = "v1_generation"
harness = false
